/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SubmissionId = IDL.Nat;
export const ActionResult = IDL.Record({
  'ok' : IDL.Bool,
  'message' : IDL.Text,
});
export const SubmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const Submission = IDL.Record({
  'id' : SubmissionId,
  'status' : SubmissionStatus,
  'screenshotFileId' : ExternalBlob,
  'submitterName' : IDL.Text,
  'collegeName' : IDL.Text,
  'submittedAt' : Timestamp,
  'submitterEmail' : IDL.Text,
  'pdfFileId' : ExternalBlob,
  'submitterAge' : IDL.Nat,
});
export const SubmitResult = IDL.Variant({
  'ok' : SubmissionId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminApprovePaper' : IDL.Func([SubmissionId, IDL.Text], [ActionResult], []),
  'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'adminRejectPaper' : IDL.Func([SubmissionId, IDL.Text], [ActionResult], []),
  'approvePaper' : IDL.Func([SubmissionId, IDL.Text], [ActionResult], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getApprovedPapers' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'rejectPaper' : IDL.Func([SubmissionId, IDL.Text], [ActionResult], []),
  'submitPaper' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob, ExternalBlob],
      [SubmitResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SubmissionId = IDL.Nat;
  const ActionResult = IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text });
  const SubmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const Submission = IDL.Record({
    'id' : SubmissionId,
    'status' : SubmissionStatus,
    'screenshotFileId' : ExternalBlob,
    'submitterName' : IDL.Text,
    'collegeName' : IDL.Text,
    'submittedAt' : Timestamp,
    'submitterEmail' : IDL.Text,
    'pdfFileId' : ExternalBlob,
    'submitterAge' : IDL.Nat,
  });
  const SubmitResult = IDL.Variant({ 'ok' : SubmissionId, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminApprovePaper' : IDL.Func(
        [SubmissionId, IDL.Text],
        [ActionResult],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'adminRejectPaper' : IDL.Func([SubmissionId, IDL.Text], [ActionResult], []),
    'approvePaper' : IDL.Func([SubmissionId, IDL.Text], [ActionResult], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getApprovedPapers' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'rejectPaper' : IDL.Func([SubmissionId, IDL.Text], [ActionResult], []),
    'submitPaper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob, ExternalBlob],
        [SubmitResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };