/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActionResult { 'ok' : boolean, 'message' : string }
export type ExternalBlob = Uint8Array;
export interface Submission {
  'id' : SubmissionId,
  'status' : SubmissionStatus,
  'screenshotFileId' : ExternalBlob,
  'submitterName' : string,
  'collegeName' : string,
  'submittedAt' : Timestamp,
  'submitterEmail' : string,
  'pdfFileId' : ExternalBlob,
  'submitterAge' : bigint,
}
export type SubmissionId = bigint;
export type SubmissionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type SubmitResult = { 'ok' : SubmissionId } |
  { 'err' : string };
export type Timestamp = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminApprovePaper' : ActorMethod<[SubmissionId, string], ActionResult>,
  'adminLogin' : ActorMethod<[string], boolean>,
  'adminRejectPaper' : ActorMethod<[SubmissionId, string], ActionResult>,
  'approvePaper' : ActorMethod<[SubmissionId, string], ActionResult>,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getApprovedPapers' : ActorMethod<[], Array<Submission>>,
  'rejectPaper' : ActorMethod<[SubmissionId, string], ActionResult>,
  'submitPaper' : ActorMethod<
    [string, string, bigint, string, ExternalBlob, ExternalBlob],
    SubmitResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];